# Site
repository: emilyhmarkowitz/emilyhmarkowitz
# favicon: images/favicon.ico

# Personal info
name: Emily Markowitz
title: Environmental Policy Analyst
website: https://github.com/emilyhmarkowitz/

# Social links
twitter_username: @emilyhmarkowitz
instagram_username: @emilymarkowitz
github_username:  @emilyhmarkowitz
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: emilyhmarkowitz
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Em! 

# Projects Section
# projects_title: Git Hub Repositories + Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and coding some of my other interests and hobbies are:
   - Volunteering at a local Women's shelter
   - NY Blood Center Gallon Club
   - Hiking
   - Traveling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
